CarShop/Controllers/ShopCartController.cs
using System.Linq;
using CarShop.Interfaces;
using CarShop.Models;
using CarShop.ViewModels;
using Microsoft.AspNetCore.Mvc;


namespace CarShop.Controllers
{
    public class ShopCartController : Controller
    {
        private  IAllCars _carRep;
        private readonly ShopCart _shopCart;
       
        public ShopCartController(IAllCars _carRep, ShopCart _shopCart)
        {
            this._carRep = _carRep;
            this._shopCart = _shopCart;
        }

        public ViewResult Index()
        {
            var items = _shopCart.GetShopItems();
            _shopCart.ListShopItems = items;

            var obj = new ShopCartViewModel
            {
                shopCart = _shopCart
            };

            return View(obj);
        }

        public RedirectToActionResult addToCart(int id)
        {
            var item = _carRep.AllCars.FirstOrDefault(i => i.Id == id);
            if (item != null)
            {
                _shopCart.AddToCart(item);
            }
            return RedirectToAction("Index");
        }
    }
}

CarShop/Views/Shared/AllCars.cshtml
@addTagHelper *,Microsoft.AspNetCore.Mvc.TagHelpers
@using CarShop.Models
@model Car

<div class="col-lg-4">
    <img class="img-thumbnail" src="@Model.Img" alt="@Model.Name" />
    <h2>@Model.Name</h2>
    <p>@Model.ShortDesc</p>
    <p>Price: @Model.Price.ToString("c")</p>
    <p><a class="btn btn-warning" asp-controller="ShopCart" asp-action="addToCart" asp-route-id="@Model.Id">Добавити в корзину</a></p>
</div>

CarShop/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/css/Style.css" rel="stylesheet" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-md navbar-dark bg-dark">
            <a class="navbar-brand" href="/">CarShop</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/Cars/List">All Cars</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/Cars/List/elektro">Elektro Automobiles</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/Cars/List/fuel">Classical Automobiles</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/ShopCart/">Cart</a>
                    </li>
                </ul>
                <form class="form-inline mt-2 mt-md-0">
                    <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
                    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                </form>
            </div>
        </nav>
    </header>
    <div class="container mt-5">
        @RenderBody()
    </div>
    <footer class="container">
        <p class="float-right"><a href="#">Back to top</a></p>
        <p>© 2019 Всі права захищені · <a href="#">Privacy</a></p>
    </footer>
    <script src="~/js/bootstrap.min.js"></script>
</body>
</html>